In [1]:
import pandas as pd

## Model Training

In [2]:
df = pd.read_csv('data/gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [3]:
df = df.drop(labels=['id'],axis=1)
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [4]:
## Independent and Dependent Features
X = df.drop(labels=['price'],axis=1)
y = df[["price"]]
print(X,"\n",y)

        carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]
         price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [5]:
y = y.values.ravel()

In [6]:
## Segregate Numerical and Categorical columns

numerical_columns = X.columns[X.dtypes!='object'].to_list()
categorical_columns = X.columns[X.dtypes=='object'].to_list()
print("Numerical Columns: ",numerical_columns)
print("Categorical Columns: ",categorical_columns)

Numerical Columns:  ['carat', 'depth', 'table', 'x', 'y', 'z']
Categorical Columns:  ['cut', 'color', 'clarity']

In [7]:
# Define the custom ranking for each ordinal variable

cut_categories = ['Fair','Good','Very Good','Premium','Ideal']
color_categories = ['D','E','F','G','H','I','J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [8]:
from sklearn.impute import SimpleImputer ## Handling Missing Values
from sklearn.preprocessing import StandardScaler, OrdinalEncoder ## Handling Feature Scaling & Ordinal Encoding
## Pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer ## For combining two pipelines

## Data Transformation Component

In [9]:
# Numerical Pipeline
num_pipeline = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),  # Step 1: Fill missing values with the median of the column
        ('scaler', StandardScaler())  # Step 2: Scale the numerical features to have a mean of 0 and a standard deviation of 1
    ]
)

# Categorical Pipeline
cat_pipeline = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),  # Step 1: Fill missing values with the most frequent category in the column
        ('ordinalencoder', OrdinalEncoder(categories=[cut_categories, color_categories, clarity_categories])),  # Step 2: Encode categorical variables into numerical values based on predefined categories
        ('scaler', StandardScaler())  # Step 3: Scale the encoded categorical features (may or may not be necessary depending on the model)
    ]
)

# Preprocessor: Combines the numerical and categorical pipelines into one
preprocessor = ColumnTransformer([
    ('num_pipeline', num_pipeline, numerical_columns),  # Apply the numerical pipeline to the specified numerical columns
    ('cat_pipeline', cat_pipeline, categorical_columns)  # Apply the categorical pipeline to the specified categorical columns
])

In [11]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=30)

print(X_train.head(),'\n\n',X_test.head(),'\n\n\n')

        carat        cut color clarity  depth  table     x     y     z
33748    1.01       Fair     F     VS2   65.3   56.0  6.21  6.16  4.05
189776   0.40      Ideal     G     SI1   61.9   57.0  4.74  4.78  2.94
17703    1.13  Very Good     H     SI1   61.6   59.0  6.63  6.71  4.12
151542   0.70      Ideal     I     VS2   62.1   56.0  5.66  5.71  3.53
3795     0.54      Ideal     H     VS1   61.2   58.0  5.20  5.24  3.20

         carat        cut color clarity  depth  table     x     y     z
70432    0.53    Premium     E     VS2   60.8   56.0  5.24  5.21  3.19
64839    0.71  Very Good     H     SI1   62.9   57.0  5.67  5.69  3.56
185316   0.30      Ideal     H      IF   62.1   57.0  4.27  4.29  2.66
84658    1.24    Premium     G     VS2   61.6   61.0  6.88  6.82  4.21
31953    0.36    Premium     E     VS1   60.4   58.0  4.60  4.63  2.80

In [12]:
# Convert transformed training and testing data into DataFrames with appropriate column names
X_train = pd.DataFrame(preprocessor.fit_transform(X_train), columns=preprocessor.get_feature_names_out())
X_test = pd.DataFrame(preprocessor.transform(X_test), columns=preprocessor.get_feature_names_out())

# Display the first few rows of the transformed data
print(X_train.head(), '\n\n', X_test.head())

   num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0             0.473767             3.220176            -0.641637
1            -0.845697             0.075806            -0.120391
2             0.733333            -0.201638             0.922103
3            -0.196781             0.260769            -0.641637
4            -0.542870            -0.571564             0.400856

   num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0         0.445161         0.398319         0.747248          -3.151612
1        -0.880410        -0.854100        -0.862659           0.873627
2         0.823895         0.897472         0.848774          -1.138993
3        -0.050801        -0.010079        -0.006943           0.873627
4        -0.465605        -0.436627        -0.485564           0.873627

   cat_pipeline__color  cat_pipeline__clarity
0            -0.318068               0.019657
1             0.297795              -0.646663
2             0.913659              -0.646663
3             1.529522               0.019657
4             0.913659               0.685978

    num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0            -0.564500            -0.941490            -0.641637
1            -0.175150             1.000621            -0.120391
2            -1.062003             0.260769            -0.120391
3             0.971269            -0.201638             1.964596
4            -0.932220            -1.311416             0.400856

   num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0        -0.429535        -0.463854        -0.500067          -0.132683
1        -0.041783        -0.028230         0.036568          -1.138993
2        -1.304232        -1.298800        -1.268762           0.873627
3         1.049332         0.997302         0.979307          -0.132683
4        -1.006654        -0.990233        -1.065710          -0.132683

   cat_pipeline__color  cat_pipeline__clarity
0            -0.933932               0.019657
1             0.913659              -0.646663
2             0.913659               2.684938
3             0.297795               0.019657
4            -0.933932               0.685978

## Model Training

In [13]:
# Importing necessary regression models and evaluation metrics from scikit-learn

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor, GradientBoostingRegressor
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [14]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted))
    r2_score_ = r2_score(true,predicted)
    return mae,mse,rmse,r2_score_

## Model Evaluation

In [15]:
# Define models and their hyperparameters for GridSearchCV
model_params = {
    'LinearRegression': {
        'model': LinearRegression(),
        'params': {}
    },
    'Lasso': {
        'model': Lasso(),
        'params': {'alpha': [0.1, 0.5, 1.0, 2.0, 5.0]}
    },
    'Ridge': {
        'model': Ridge(),
        'params': {'alpha': [0.1, 0.5, 1.0, 2.0, 5.0]}
    },
    'ElasticNet': {
        'model': ElasticNet(),
        'params': {
            'alpha': [0.1, 0.5, 1.0, 2.0, 5.0],
            'l1_ratio': [0.2, 0.5, 0.8]
        }
    },
    'AdaBoostRegressor': {
        'model': AdaBoostRegressor(),
        'params': {
            'n_estimators': [50, 100],
            'learning_rate': [0.01, 0.1]
        }
    },
    'DecisionTreeRegressor': {
        'model': DecisionTreeRegressor(),
        'params': {
            'max_depth': [5, 10, 20, 40, 50],
            'min_samples_split': [2, 10]
        }
    },
    'RandomForestRegressor': {
        'model': RandomForestRegressor(),
        'params': {
            'n_estimators': [50, 100],
            'max_depth': [10,20,]
        }
    },
    'KNeighborsRegressor': {
        'model': KNeighborsRegressor(),
        'params': {
            'n_neighbors': [5, 10],
            'weights': ['uniform', 'distance']
        }
    },
    'GradientBoostingRegressor': {
        'model': GradientBoostingRegressor(),
        'params': {
            'n_estimators': [50, 100],
            'learning_rate': [0.1, 0.2, 0.5],
            'max_depth': [3, 5, 10]
        }
    },
    'XGBoost': {
        'model': xgb.XGBRegressor(),
        'params': {
            'n_estimators': [50, 100],
            'learning_rate': [0.1, 0.2, 0.5],
            'max_depth': [3, 5, 10]
        }
    }
}

# To store results
best_models = {}
r2_list = []

# Iterate over all models
for model_name, model_data in model_params.items():
    print(f"Running GridSearchCV for {model_name}...")
    
    # GridSearchCV
    grid_search = GridSearchCV(
        estimator=model_data['model'],
        param_grid=model_data['params'],
        scoring='r2',
        cv=5,
        n_jobs=-1
    )
    grid_search.fit(X_train, y_train)
    
    # Get best model and results
    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Make Predictions
    y_pred = best_model.predict(X_test)
    mae, mse, rmse, r2_score_ = evaluate_model(y_test, y_pred)
    
    # Store results
    best_models[model_name] = {
        'model': best_model,
        'params': best_params,
        'r2_train': best_score,
        'r2_test': r2_score_
    }
    r2_list.append(r2_score_)

    # Print results
    print(f"Best Params for {model_name}: {best_params}")
    print(f"Train R2 Score (CV): {best_score}")
    print("Test Performance:")
    print(f"  RMSE: {rmse}")
    print(f"  MSE: {mse}")
    print(f"  MAE: {mae}")
    print(f"  R2 Score: {r2_score_}")
    print("=" * 50)
    print("\n")

# Identify the best model
best_model_name = max(best_models, key=lambda x: best_models[x]['r2_test'])
print(f"Best Model: {best_model_name}")
print(f"Parameters: {best_models[best_model_name]['params']}")

Running GridSearchCV for LinearRegression...
Best Params for LinearRegression: {}
Train R2 Score (CV): 0.9365702053645244
Test Performance:
  RMSE: 1020.9106955021983
  MSE: 1042258.6481907823
  MAE: 677.565219031756
  R2 Score: 0.9363482324438801
==================================================


Running GridSearchCV for Lasso...
Best Params for Lasso: {'alpha': 1.0}
Train R2 Score (CV): 0.9366884202311152
Test Performance:
  RMSE: 1020.8783432223119
  MSE: 1042192.5916603324
  MAE: 678.6412565975306
  R2 Score: 0.9363522665815954
==================================================


Running GridSearchCV for Ridge...
Best Params for Ridge: {'alpha': 0.1}
Train R2 Score (CV): 0.9365701779871014
Test Performance:
  RMSE: 1020.910668336889
  MSE: 1042258.5927240733
  MAE: 677.5679166470608
  R2 Score: 0.9363482358312869
==================================================


Running GridSearchCV for ElasticNet...
Best Params for ElasticNet: {'alpha': 0.1, 'l1_ratio': 0.8}
Train R2 Score (CV): 0.9250528895222508
Test Performance:
  RMSE: 1108.8611439357912
  MSE: 1229573.0365305915
  MAE: 795.0302800185301
  R2 Score: 0.9249087572932361
==================================================


Running GridSearchCV for AdaBoostRegressor...
Best Params for AdaBoostRegressor: {'learning_rate': 0.1, 'n_estimators': 50}
Train R2 Score (CV): 0.9294305927373951
Test Performance:
  RMSE: 1069.4584246790353
  MSE: 1143741.3221169638
  MAE: 688.9375246492347
  R2 Score: 0.9301505850720538
==================================================


Running GridSearchCV for DecisionTreeRegressor...
Best Params for DecisionTreeRegressor: {'max_depth': 10, 'min_samples_split': 10}
Train R2 Score (CV): 0.9756145986398627
Test Performance:
  RMSE: 632.6413207500295
  MSE: 400235.0407203418
  MAE: 325.72744651552057
  R2 Score: 0.9755572498016998
==================================================


Running GridSearchCV for RandomForestRegressor...
Best Params for RandomForestRegressor: {'max_depth': 10, 'n_estimators': 100}
Train R2 Score (CV): 0.9783888678880585
Test Performance:
  RMSE: 595.9213103655187
  MSE: 355122.2081477569
  MAE: 306.82722321639164
  R2 Score: 0.9783123351518601
==================================================


Running GridSearchCV for KNeighborsRegressor...
Best Params for KNeighborsRegressor: {'n_neighbors': 10, 'weights': 'distance'}
Train R2 Score (CV): 0.9731658395596587
Test Performance:
  RMSE: 651.4965657055262
  MSE: 424447.775126095
  MAE: 338.2081373431119
  R2 Score: 0.97407855413919
==================================================


Running GridSearchCV for GradientBoostingRegressor...
Best Params for GradientBoostingRegressor: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
Train R2 Score (CV): 0.9794922126146819
Test Performance:
  RMSE: 581.8142945564927
  MSE: 338507.87335026916
  MAE: 298.85847935339007
  R2 Score: 0.9793269890273304
==================================================


Running GridSearchCV for XGBoost...
Best Params for XGBoost: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
Train R2 Score (CV): 0.9795689225677101
Test Performance:
  RMSE: 582.3610174319613
  MSE: 339144.3546243891
  MAE: 298.87278923813153
  R2 Score: 0.9792881184857576
==================================================


Best Model: GradientBoostingRegressor
Parameters: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}